Repository Who-put-that-in-my-drive/Moments, pull requests merged in 2022-11, with the labels that each got.

#40 added logout and login functionality with user update in store and lo…
  .eslintrc.json
  client/src/components/Header.tsx
  client/src/components/PhotoCard.tsx
  client/src/components/SideNavBar.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Login.tsx
  client/src/pages/Uploads.tsx
  client/src/store/store.tsx
  client/src/store/tempData.jsx
  package.json
  server/src/routes/api/auth.ts
Labels: Front-end

#46 Creating Api-Gateway resources for our User api's
  aws/serverless-configs/resources/api-gateway.yml
Labels: AWS-cloud

#41 Profile page initial template
  .DS_Store
  client/src/App.tsx
  client/src/pages/Profile.tsx
Labels: Front-end

#54 Cleaning up api request code
  client/src/ProtectedRoutes.tsx
  client/src/components/SideNavBar.tsx
  client/src/interfaces/Image.ts
  client/src/interfaces/User.ts
  client/src/interfaces/UserStore.ts
  client/src/pages/Login.tsx
  client/src/pages/Register.tsx
  client/src/pages/Uploads.tsx
  client/src/services/api.service.tsx
  client/src/services/api/auth-service.ts
  client/src/services/api/user-service.ts
  client/src/store/store.tsx
  client/src/utils/Interfaces.ts
  client/src/utils/WebsiteUtils.ts
Labels: Front-end

#48 Feat/postpage
  client/package.json
  client/src/App.tsx
  client/src/assets/images/Beach.jpg
  client/src/pages/Post.tsx
Labels: Front-end

#57 User update feature
  .gitignore
  client/src/App.tsx
  client/src/interfaces/UserStore.ts
  client/src/pages/Login.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Register.tsx
  client/src/services/api/user-service.ts
  client/src/store/store.tsx
  client/src/utils/ResponseUtils.ts
  client/src/utils/WebsiteUtils.ts
  server/src/interfaces/auth/SanitizedUser.ts
  server/src/interfaces/user/UpdateUserDTO.ts
  server/src/routes/api/user.ts
Labels: Front-end

#70 Feat/dashboard additions
  client/src/pages/Dashboard.tsx
  client/src/pages/Post.tsx
  client/src/pages/Uploads.tsx
Labels: Front-end

#75 fixed some small changes and added search/sort feature for uploads page
  client/src/components/PhotoCard.tsx
  client/src/interfaces/Image.ts
  client/src/interfaces/UserStore.ts
  client/src/pages/Landing.tsx
  client/src/pages/Uploads.tsx
  client/src/store/store.tsx
Labels: documentation, Front-end

#78 Profile upload feature
  client/src/assets/images/Beach.jpg
  client/src/components/DragAndDrop.tsx
  client/src/components/PhotoCard.tsx
  client/src/components/SideNavBar.tsx
  client/src/components/UploadModal.tsx
  client/src/interfaces/User.ts
  client/src/interfaces/UserStore.ts
  client/src/pages/Login.tsx
  client/src/pages/Post.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Uploads.tsx
  client/src/services/api/image-service.ts
  client/src/store/store.tsx
  server/src/routes/api/auth.ts
Labels: enhancement, Front-end

#84 Updating profile avatar image server logic
  server/src/interfaces/auth/User.ts
  server/src/interfaces/user/UpdateAvatarImageDTO.ts
  server/src/models/user.model.ts
  server/src/routes/api/auth.ts
  server/src/routes/api/user/avatar.ts
Labels: Back-end

#85 Adding batch retrieval
  aws/serverless-configs/resources/api-gateway.yml
  server/src/routes/api/images.ts
Labels: Back-end

#86 Images fetch feature
  client/src/components/PhotoCard.tsx
  client/src/components/UploadModal.tsx
  client/src/interfaces/Image.ts
  client/src/interfaces/User.ts
  client/src/pages/Explore.tsx
  client/src/pages/Uploads.tsx
  client/src/services/api/image-service.ts
  client/src/utils/ComponentPropTypes.ts
Labels: Front-end
